# Generated by Django 5.1.1 on 2024-10-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_ec_number', models.CharField(default='еЦ_.___.___-__', max_length=100, unique=True, verbose_name='Номер еЦ')),
                ('info_product_family', models.CharField(max_length=100, verbose_name='Семейство изделия')),
                ('info_product_family_code', models.PositiveIntegerField(verbose_name='Код семейства изделия')),
                ('info_revision', models.PositiveIntegerField(verbose_name='Ревизия')),
                ('info_revision_code', models.PositiveIntegerField(verbose_name='Код ревизии')),
                ('info_product_type', models.CharField(max_length=100, verbose_name='Тип изделия')),
                ('info_product_type_code', models.PositiveIntegerField(verbose_name='Код типа изделия')),
                ('info_manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('info_manufacturer_code', models.PositiveIntegerField(verbose_name='Код производителя')),
            ],
        ),
        migrations.CreateModel(
            name='Serial_Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_field', models.TextField(blank=True, unique=True, verbose_name='Объединенное поле')),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_count', models.PositiveIntegerField(verbose_name='Количество изделий')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('history', models.TextField(max_length=10000, verbose_name='История изделия')),
                ('number_of_module', models.PositiveIntegerField(verbose_name='Номер изделия')),
                ('ec_number', models.ForeignKey(db_column='ec_number', default='еЦ_.___.___-__', on_delete=django.db.models.deletion.CASCADE, related_name='regs', to='main.info_modules', to_field='info_ec_number', verbose_name='Номер еЦ')),
            ],
        ),
        migrations.CreateModel(
            name='remont',
            fields=[
                ('remont_id', models.AutoField(primary_key=True, serialize=False)),
                ('remont_otchet', models.CharField(max_length=1000000, verbose_name='Отчет')),
                ('remont_info', models.CharField(max_length=1000000, verbose_name='Информация')),
                ('serial_number', models.ForeignKey(db_column='serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер')),
            ],
        ),
        migrations.CreateModel(
            name='proverka',
            fields=[
                ('proverka_id', models.AutoField(primary_key=True, serialize=False)),
                ('proverka_otchet', models.CharField(max_length=1000000, verbose_name='Отчет')),
                ('proverka_info', models.CharField(max_length=1000000, verbose_name='Информация')),
                ('proverka_error', models.CharField(max_length=1000000, verbose_name='Возможная причина ошибки')),
                ('serial_number', models.ForeignKey(db_column='serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер')),
            ],
        ),
        migrations.CreateModel(
            name='poverka',
            fields=[
                ('poverka_id', models.AutoField(primary_key=True, serialize=False)),
                ('poverka_otchet', models.CharField(max_length=1000000, verbose_name='Отчет')),
                ('poverka_info', models.CharField(max_length=1000000, verbose_name='Информация')),
                ('poverka_error', models.CharField(max_length=1000000, verbose_name='Возможная причина ошибки')),
                ('serial_number', models.ForeignKey(db_column='serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер')),
            ],
        ),
        migrations.CreateModel(
            name='kalibrovka',
            fields=[
                ('kalibrovka_id', models.AutoField(primary_key=True, serialize=False)),
                ('kalibrovka_otchet', models.CharField(max_length=1000000, verbose_name='Отчет')),
                ('kalibrovka_info', models.CharField(max_length=1000000, verbose_name='Информация')),
                ('kalibrovka_error', models.CharField(max_length=1000000, verbose_name='Возможная причина ошибки')),
                ('kalibrovka_koeff', models.CharField(max_length=1000000, verbose_name='Коэффициенты калибровки')),
                ('serial_number', models.ForeignKey(db_column='serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер')),
            ],
        ),
        migrations.CreateModel(
            name='transportirovka',
            fields=[
                ('transportirovka_id', models.AutoField(primary_key=True, serialize=False)),
                ('transportirovka_nakladnaya', models.CharField(max_length=1000000, verbose_name='Номер накладной')),
                ('transportirovka_iz', models.CharField(max_length=1000000, verbose_name='Поступил из')),
                ('transportirovka_v', models.CharField(max_length=1000000, verbose_name='Поступил в')),
                ('transportirovka_date', models.DateField(verbose_name='Дата поступления')),
                ('serial_number', models.ForeignKey(db_column='serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер')),
            ],
        ),
    ]
