# Generated by Django 5.1.1 on 2024-10-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_date_of_production', to='main.reg', verbose_name='Дата производства')),
                ('history_of_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_history_of_module', to='main.reg', verbose_name='История изделия')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_manufacturer', to='main.info_modules', verbose_name='Производитель')),
                ('number_ec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_number_ec', to='main.reg', verbose_name='Номер еЦ')),
                ('product_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_product_family', to='main.info_modules', verbose_name='Семейство изделия')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_product_type', to='main.info_modules', verbose_name='Тип продукта')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_revision', to='main.info_modules', verbose_name='Ревизия')),
                ('sequence_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_sequence_number', to='main.reg', verbose_name='Номер изделия')),
                ('serial_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_serial_number', to='main.serial_numbers', verbose_name='Серийный номер')),
            ],
        ),
    ]
