# Generated by Django 5.1.1 on 2024-10-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='date_of_production_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='history_of_module_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='manufacturer_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='number_ec_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='product_family_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='product_type_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='revision_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='sequence_number_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='serial_number_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
