# Generated by Django 5.1.3 on 2024-11-19 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_modules_module_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
